[tool.poetry]
name = "ca"
version = "0.1.0"
description = ""
authors = ["Jens Langhammer <jens.langhammer@beryju.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "*"
cryptography = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
